### ISSUE TITLE
Uncaught TypeError: Cannot read property '70' of undefined

### ISSUE THREAD

**Issue by deasytech** [FabioAntunes/double-brackets-with-spaces#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [double-brackets-with-spaces](https://github.com/FabioAntunes/double-brackets-with-spaces) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property '70' of undefined

```
At C:\Users\lenovo\.atom\packages\double-brackets-with-spaces\lib\double-brackets-with-spaces.js:54

TypeError: Cannot read property '70' of undefined
    at Object.insertSpaces (/packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:54:88)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:34:22
    at Array.map (native)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:33:42
    at Array.map (native)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:31:25
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/text-buffer/lib/text-buffer.js:1581:26)
    at later (~/AppData/Local/atom/app-1.19.5/resources/app/node_modules/text-buffer/lib/helpers.js:21:13)
```

### Commands

```
     -0:51.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
blade-snippets 0.2.0 
blade-spacer 0.4.2 
double-brackets-with-spaces 2.0.2 
language-blade 0.34.0 
laravel 0.7.1 
laravel-5-snippets 0.8.0 
laravel-eloquent-snippets 2.0.0 
laravel-forms-bootstrap-snippets 1.2.0 
laravel-helper 0.2.1 
laravel-snippets 2.1.0 
laravel-syntax 0.2.0 
laravel-theme 0.3.0 
php-fmt 0.1.2 
prettify-laravel-boilerplate 1.1.1 
```

**Comment by FabioAntunes** [comment]
@deasytech it's been fixed, update the package to the latest version 2.1.0. Thanks for submitting the issue
