### ISSUE TITLE
Uncaught TypeError: Cannot read property '160' of undefined

### ISSUE THREAD

**Issue by Nfinished** [FabioAntunes/double-brackets-with-spaces#8]
Repro Steps:

1. Hit space after an opening bracket which was the last character on the line. This was in a .vue file.

**Atom**: 1.19.5 x64
**Electron**: 1.6.11
**OS**: "Arch Linux"
**Thrown From**: [double-brackets-with-spaces](https://github.com/FabioAntunes/double-brackets-with-spaces) package 2.0.2

### Stack Trace

Uncaught TypeError: Cannot read property '160' of undefined

```
At /home/adam/.atom/packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:54

TypeError: Cannot read property '160' of undefined
    at Object.insertSpaces (/packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:54:88)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:34:22
    at Array.map (native)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:33:42
    at Array.map (native)
    at /packages/double-brackets-with-spaces/lib/double-brackets-with-spaces.js:31:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1563:20)
    at later (/usr/lib/atom/node_modules/text-buffer/lib/helpers.js:21:7)
```

### Commands

```
     -7:04.3.0 core:backspace (input.hidden-input)
  2x -7:04.1.0 core:confirm (input.hidden-input)
     -6:02.6.0 intentions:highlight (input.hidden-input)
     -6:02.5.0 settings-view:open (input.hidden-input)
     -0:07.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
busy-signal 1.4.3 
color-picker 2.2.5 
double-brackets-with-spaces 2.0.2 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.11 
git-blame 1.2.2 
git-time-machine 1.5.9 
gruvbox-plus-syntax 1.3.1 
intentions 1.1.5 
intentions-colorpicker 1.0.1 
language-javascript-jsx 0.3.7 
language-pug 0.0.21 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
```

**Comment by Nfinished** [comment]
'160' seems to be the line number.

**Comment by FabioAntunes** [comment]
I'm going to be honest it's been a while since o have used Atom but I will
take a look as soon as I can. Feel free to send a pull request
